# Generated by Django 5.0 on 2023-12-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('amount', models.FloatField()),
                ('carbohydrate', models.FloatField()),
                ('protein', models.FloatField()),
                ('total_fat', models.FloatField()),
                ('trans_fat', models.FloatField()),
                ('saturated_fat', models.FloatField()),
                ('fiber', models.FloatField()),
                ('sodium', models.FloatField()),
                ('calory', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
