# Generated by Django 5.0 on 2023-12-23 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('total_carbohydrate', models.FloatField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_total_fat', models.FloatField(default=0)),
                ('total_trans_fat', models.FloatField(default=0)),
                ('total_saturated_fat', models.FloatField(default=0)),
                ('total_fiber', models.FloatField(default=0)),
                ('total_sodium', models.FloatField(default=0)),
                ('total_calory', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbohydrate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='saturated_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='total_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='trans_fat',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culinary_registry.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culinary_registry.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='culinary_registry.RecipeIngredient', to='culinary_registry.ingredient'),
        ),
    ]
